### ISSUE TITLE
npm run build gives a timeout warning

### ISSUE THREAD

**Issue by kefahi** [sveltech/ssr#10]
When running `npm run build` (latest routify) I get couple of warnings (full console dump below)

1. First warning is `Waited for the event "app-loaded", but timed out after 5000ms`
What can I do here? Should I manually trigger app-load event? (I tried calling $ready just to silence the warning without avail). 

2. Second warning is `UnhandledPromiseRejectionWarning: Unhandled promise rejection. `
The problem here is SSR uses javascript eval to evaluate the whole code and I have no means (that I'm aware of) to see the warning on the specific offensive code.

Your help is greatly appreciated. 

```
npm run build

> imx-svelte-frontend@0.0.1 build /home/kefah/Development/imx/svelte_frontend
> run-s build:*


> imx-svelte-frontend@0.0.1 build:app /home/kefah/Development/imx/svelte_frontend
> routify -b && rollup -c

[Routify] Generated routes in 1 ms

src/main.js → dist/build...

The service worker file was written to dist/serviceworker.js
The service worker will precache 19 URLs, totaling 2.14 MB.

created dist/build in 19.8s

> imx-svelte-frontend@0.0.1 build:static /home/kefah/Development/imx/svelte_frontend
> spank

spank found config for Routify 2
⠹ Exporting 14 of 33 /tag/posts[tossr] /managed/tools/console Waited for the event "app-loaded", but timed out after 5000 ms.
⠼ Exporting 15 of 33 /entry/posts/doc/ayyash[tossr] /managed/tools/query Waited for the event "app-loaded", but timed out after 5000 ms.
⠙ Exporting 32 of 33 /tag/posts/about(node:47258) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'createElement' of undefined
(Use `node --trace-warnings ...` to show where the warning was created)
(node:47258) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:47258) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
⠴ Exporting 33 of 33 /tag/posts/imx(node:47258) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'createElement' of undefined
(node:47258) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
✔ Exported 33 pages (0 ignored) from total 33 pages in 9448 ms
```

**Comment by jakobrosenberg** [comment]
The first error is most likely caused by a `<slot />` never rendering. Eg. `{#if unmetCondition} <slot /> {/if}`
The second error I assume is caused by async code resolving after the page has been closed and rendered to HTML.

Both issues should be solvable by using `$ready`. Since you've already tried this, I'd recommend checking parent layouts or imported components for async calls.

**Comment by kefahi** [comment]
> The first error is most likely caused by a `<slot />` never rendering. Eg. `{#if unmetCondition} <slot /> {/if}`
> The second error I assume is caused by async code resolving after the page has been closed and rendered to HTML.
> 
> Both issues should be solvable by using `$ready`. Since you've already tried this, I'd recommend checking parent layouts or imported components for async calls.

Many thanks for the tip.

Indeed using $ready() solved both issues. I just had to know where to use $ready(). In one case I used it in _fallback and in another I used it in _reset. 

Closing this issue!
