### ISSUE TITLE
Updade JSDOM usage to be run in node.js

### ISSUE THREAD

**Issue by Egnus** [sveltech/ssr#6]
I wish i could use this but sadly building this in firebase cloud functions require the code to be compatible for node.js.
Otherwise it will get errors like `ReferenceError: TextEncoder is not defined` 

Is it there any way you will support this in the future?

**Comment by jakobrosenberg** [comment]
Tossr and JSDOM are both intended to run in node, so node support is already there.

I haven't tried Firebase, but you could try a search on our Routify Discord and have a look at the experiences shared there.

**Comment by jakobrosenberg** [comment]
In case this is still an issue, here's a possible fix:

```javascript
//tossr.config.js
module.exports = {
  beforeEval(dom => 
    dom.window.TextEncoder = require('util').TextEncoder
  )  
}
```
